const $=s=>document.querySelector(s);const api=async(path,options={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Ошибка ${r.status}`);return data};
const notify=(m,bad=false)=>{const n=$('#notice');n.textContent=m;n.style.background=bad?'#f8ebe9':'';n.style.color=bad?'#a83b35':'';setTimeout(()=>{n.textContent='';n.style=''},5000)};
async function boot(){try{const me=await api('/api/me');$('#login').hidden=true;$('#panel').hidden=false;$('#currentUser').textContent=me.username;await Promise.all([loadSettings(),loadStatus()])}catch{$('#login').hidden=false;$('#panel').hidden=true}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});await boot()}catch(x){$('#loginError').textContent=x.message}});
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
async function loadSettings(){const s=await api('/api/settings');for(const k of ['provider','transport','providerAddress','room','listenAddress','listenPort','destination','autoStart']){const el=$('#'+k);if(el.type==='checkbox')el.checked=s[k];else el.value=s[k]??''}}
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const s={provider:$('#provider').value,transport:$('#transport').value,providerAddress:$('#providerAddress').value,room:$('#room').value,listenAddress:$('#listenAddress').value,listenPort:Number($('#listenPort').value),destination:$('#destination').value,autoStart:$('#autoStart').checked};try{await api('/api/settings',{method:'PUT',body:JSON.stringify(s)});notify('Конфигурация сохранена в .env')}catch(x){notify(x.message,true)}});
async function loadStatus(){try{const s=await api('/api/status');$('#statusText').textContent=s.status;$('#version').textContent=s.version||'—';$('#currentVersion').textContent=s.version||'—';$('#projectDir').textContent=s.projectDir;$('#topStatus').textContent=(s.active?'● Сервер работает':'○ Сервер остановлен');$('#topStatus').style.background=s.active?'':'#eee'}catch(x){notify(x.message,true)}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/service/'+b.dataset.action,{method:'POST'});notify('Команда выполнена');await loadStatus()}catch(x){notify(x.message,true)}finally{b.disabled=false}});
$('#checkUpdate').onclick=async()=>{const b=$('#checkUpdate');b.disabled=true;try{const u=await api('/api/update/check',{method:'POST'});$('#currentVersion').textContent=u.current||'не установлена';$('#latestVersion').textContent=u.latest;$('#installUpdate').disabled=!u.available;notify(u.available?'Доступна новая версия':'Установлена актуальная версия')}catch(x){notify(x.message,true)}finally{b.disabled=false}};
$('#installUpdate').onclick=async()=>{const b=$('#installUpdate');b.disabled=true;b.textContent='Обновляем…';try{const x=await api('/api/update/install',{method:'POST'});notify(x.message);await loadStatus()}catch(x){notify(x.message,true)}finally{b.textContent='Обновить';b.disabled=false}};
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));boot();
